import { formatDateP, formatCurrency, } from 'src/reusable/Util'

export function getPrintEntrega(resultados) {
  console.log("getPrintEntrega");
  
  let infoRecibo = "";
  resultados.forEach(resultado => {
    if (resultado.valuesEntregas.length > 0) {
      resultado.valuesEntregas.forEach(element => {
        if (element.entrega != null) {
          let tipoDcto = element.entrega.Completo ? "FA" : "RE";
          infoRecibo += "</br><table width='100%'>";
          infoRecibo += "<tbody>";
          infoRecibo += "  <tr>";
          infoRecibo += "    <td colspan='2'>";
          infoRecibo += "      <img class='c-sidebar-brand-full' src='https://static.wixstatic.com/media/86007f_0b4a795108ad425dabf0bc7ed3c67106~mv2.png/v1/fill/w_192,h_51,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/86007f_0b4a795108ad425dabf0bc7ed3c67106~mv2.png' height='50' alt='logo-negative' /></td>";
          infoRecibo += "    <td colspan='2' width='350px'>";
          infoRecibo += "      900277244-4</br>";
          infoRecibo += "      Sede Principal: Carrera 43a N.34 95 Local 298</br>";
          infoRecibo += "      Tel: (4)3220689</br>";
          infoRecibo += "      <table width='100%'><tr>";
          infoRecibo += "        <td>www.helpharma.com</td>";
          infoRecibo += "        <td align='right'>";
          infoRecibo += "          <div style={{ fontWeight: 'bold', marginRight: '30px' }}> " + element.entrega.Completo ? 'SOPORTE ENTREGA' : 'REMISIÓN' + "</div>";
          infoRecibo += "        </td>";
          infoRecibo += "      </tr></table>";
          infoRecibo += "      <table width='100%'><tr>";
          infoRecibo += "        <td>Medellin-Colombia</td>";
          infoRecibo += "        <td align='right'>";
          infoRecibo += "          <div style={{ fontWeight: 'bold', marginRight: '30px' }}><p>No. " + element.entrega.prefijoEntrega + "</p></div>";
          infoRecibo += "        </td>";
          infoRecibo += "      </tr></table>";
          infoRecibo += "    </td>";
          infoRecibo += "    <td colspan='2'>";
          infoRecibo += "      <img class='c-sidebar-brand-full' src='https://www.latiendadelasbarras.com/wp-content/uploads/2019/07/codigo-39-barras.jpg' height='50' alt='logo-negative' />";
          infoRecibo += "    </td>";
          infoRecibo += "  </tr>";
          infoRecibo += "</tbody>";
          infoRecibo += "</table>";
          infoRecibo += "<br>";
          infoRecibo += "<table border={'1px solid black;'} width='100%'>";
          infoRecibo += "     <tr>";
          infoRecibo += "        <th rowspan='2' style={{ width: '400px' }}>SEÑORES:" + element.entrega.Convenio.Nombre + "";
          infoRecibo += "           </br>Telefono:";
          infoRecibo += "          </br>Ciudad:";
          infoRecibo += "        </th>";
          infoRecibo += "        <td>";
          infoRecibo += "          <table width='100%' ><tr>";
          infoRecibo += "            <td><b>FECHA:</b> " + formatDateP(element.entrega.Fecha, 'D MMM YYYY') + "</td>";
          infoRecibo += "             <td><b>BODEGA:</b> " + element.entrega.IdBodega + "</td>";
          infoRecibo += "          </tr></table>";
          infoRecibo += "        </td>";
          infoRecibo += "      </tr>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td><b>PACIENTE:</b> " + element.entrega.Paciente.Nombre + "</td>";
          infoRecibo += "      </tr>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td>";
          infoRecibo += "          <b>TIPO DE VENTA</b></br> " + element.entrega.TipoEntrega.Nombre + "</td>";
          infoRecibo += "        <td>";
          infoRecibo += "          <table width='100%'>";
          infoRecibo += "            <tr><td><b>CEDULA O NIT</b></br>" + element.entrega.Paciente.IdPaciente + "</td>";
          infoRecibo += "            <td><b>TIPO PLAN</b></br>POS</td>";
          infoRecibo += "            <td><b>TIPO CARTERA</b></br>" + element.entrega.IdCartera + "</td>";
          infoRecibo += "            <td><b>TIPO DCTO</b></br>" + tipoDcto + "</td>";
          infoRecibo += "          </tr></table></td>";
          infoRecibo += "      </tr>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td colspan='2'>";
          infoRecibo += "          <table width='100%'>";
          infoRecibo += "            <tr><td><b>DIRECCION:</b>" + element.entrega.Paciente.Direccion + "</td><td><b>BARRIO:</b>" + element.entrega.Paciente.Barrio + "</td></tr>";
          infoRecibo += "            <tr><td><b>TELEFONO:</b>" + element.entrega.Paciente.Telefono + "</td><td><b>CELULAR:</b>" + element.entrega.Paciente.Celular + "</td></tr>";
          infoRecibo += "            <tr><td colspan='3' height={'50'}><b>OBSERVACIONES:</b>" + element.entrega.Paciente.Comentario + "</td></tr>";
          infoRecibo += "          </table></td>";
          infoRecibo += "     </tr>";
          infoRecibo += "    </table>";
          infoRecibo += "    </br>";
          infoRecibo += "<table border={'1px solid black;'} width='100%'>";
          infoRecibo += "       <tr>";
          infoRecibo += "        <th>Orden</th>";
          infoRecibo += "        <th>Descripcion</th>";
          infoRecibo += "        <th>Cantidad</th>";
          infoRecibo += "        <th>Vr. Unitario</th>";
          infoRecibo += "        <th>Total</th></tr>";
          infoRecibo += "      <tbody>";
          let TpEntregaMvto = element.mvEntrega ? element.mvEntrega : (element.mvEntregas ? element.mvEntregas : null);
          TpEntregaMvto.forEach(elemento => {
            infoRecibo += " <tr>";
            infoRecibo += "          <td>" + elemento.Orden + "</td>";
            infoRecibo += "          <td>" + elemento.Nombre + "</td>";
            infoRecibo += "          <td>" + elemento.QtyEntrega + "</td>";
            infoRecibo += "          <td>" + formatCurrency('en-US', 'USD', 0, elemento.Valor) + "</td>";
            infoRecibo += "          <td>" + formatCurrency('en-US', 'USD', 0, (elemento.Valor * elemento.QtyEntrega)) + "</td>";
            infoRecibo += "        </tr>";
          });
          infoRecibo += "</tbody>";
          infoRecibo += "<tfoot>";
          infoRecibo += "        <tr>";
          infoRecibo += "          <td></td>";
          infoRecibo += "          <td>Cuota moderadora</td>";
          infoRecibo += "          <td></td>";
          infoRecibo += "          <td> " + formatCurrency('en-US', 'USD', 0, element.entrega.ValorCM) + "</td>";
          infoRecibo += "          <td></td>";
          infoRecibo += "        </tr>";
          infoRecibo += "        <tr>";
          infoRecibo += "          <td></td>";
          infoRecibo += "          <td>Valor a Pagado</td>";
          infoRecibo += "          <td></td>";
          infoRecibo += "          <td>" + formatCurrency('en-US', 'USD', 0, element.entrega.Pagado) + "</td>";
          infoRecibo += "          <td></td>";
          infoRecibo += "        </tr>";
          infoRecibo += "      </tfoot>";
          infoRecibo += "    </table>";
          infoRecibo += "    </br>";
          infoRecibo += "<table width='100%'>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td>___" + element.entrega.IdUser_Ing + "___</td>";
          infoRecibo += "        <td>_______________________________________________________</td>";
          infoRecibo += "        <td>________________________________</td>";
          infoRecibo += "      </tr>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td>Elaborado Por</td>";
          infoRecibo += "        <td>Nombre Quien Recibe</td>";
          infoRecibo += "        <td>Identificacion Quien Recibe</td>";
          infoRecibo += "      </tr>";
          infoRecibo += "    </table>";
        }
      });
    }
    if (resultado.valuesPendientes.length > 0) {
      resultado.valuesPendientes.forEach(element => {
        if (element.pendiente != null) {
          console.log(element);
          infoRecibo += "</br><table width='100%'>";
          infoRecibo += "<tbody>";
          infoRecibo += "  <tr>";
          infoRecibo += "    <td colspan='2'>";
          infoRecibo += "      <img class='c-sidebar-brand-full' src='https://static.wixstatic.com/media/86007f_0b4a795108ad425dabf0bc7ed3c67106~mv2.png/v1/fill/w_192,h_51,al_c,q_85,usm_0.66_1.00_0.01,enc_auto/86007f_0b4a795108ad425dabf0bc7ed3c67106~mv2.png' height='50' alt='logo-negative' /></td>";
          infoRecibo += "    <td colspan='2' width='350px'>";
          infoRecibo += "      900277244-4</br>";
          infoRecibo += "      Sede Principal: Carrera 43a N.34 95 Local 298</br>";
          infoRecibo += "      Tel: (4)3220689</br>";
          infoRecibo += "      <table width='100%'><tr>";
          infoRecibo += "        <td>www.helpharma.com</td>";
          infoRecibo += "        <td align='right'>";
          infoRecibo += "          <div style={{ fontWeight: 'bold', marginRight: '30px' }}> " + 'REMISIÓN' + "</div>";
          infoRecibo += "        </td>";
          infoRecibo += "      </tr></table>";
          infoRecibo += "      <table width='100%'><tr>";
          infoRecibo += "        <td>Medellin-Colombia</td>";
          infoRecibo += "        <td align='right'>";
          infoRecibo += "          <div style={{ fontWeight: 'bold', marginRight: '30px' }}><p>No. " + element.pendiente.Prefijo + element.pendiente.NoPendiente + "</p></div>";
          infoRecibo += "        </td>";
          infoRecibo += "      </tr></table>";
          infoRecibo += "    </td>";
          infoRecibo += "    <td colspan='2'>";
          infoRecibo += "      <img class='c-sidebar-brand-full' src='https://www.latiendadelasbarras.com/wp-content/uploads/2019/07/codigo-39-barras.jpg' height='50' alt='logo-negative' />";
          infoRecibo += "    </td>";
          infoRecibo += "  </tr>";
          infoRecibo += "</tbody>";
          infoRecibo += "</table>";
          infoRecibo += "<br>";
          infoRecibo += "<table border={'1px solid black;'} width='100%'>";
          infoRecibo += "     <tr>";
          infoRecibo += "        <th rowspan='2' style={{ width: '400px' }}>SEÑORES:" + element.pendiente.Convenio.Nombre + "";
          infoRecibo += "           </br>Telefono:";
          infoRecibo += "          </br>Ciudad:";
          infoRecibo += "        </th>";
          infoRecibo += "        <td>";
          infoRecibo += "          <table width='100%' ><tr>";
          infoRecibo += "            <td><b>FECHA:</b> " + formatDateP(element.pendiente.Fecha, 'D MMM YYYY') + "</td>";
          infoRecibo += "             <td><b>BODEGA:</b> " + element.pendiente.IdBodega + "</td>";
          infoRecibo += "          </tr></table>";
          infoRecibo += "        </td>";
          infoRecibo += "      </tr>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td><b>PACIENTE:</b> " + element.pendiente.Paciente.Nombre + "</td>";
          infoRecibo += "      </tr>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td>";
          infoRecibo += "          <b>TIPO DE VENTA</b></br> " + "" + "</td>";
          infoRecibo += "        <td>";
          infoRecibo += "          <table width='100%'>";
          infoRecibo += "            <tr><td><b>CEDULA O NIT</b></br>" + element.pendiente.Paciente.IdPaciente + "</td>";
          infoRecibo += "            <td><b>TIPO PLAN</b></br>POS</td>";
          infoRecibo += "            <td><b>TIPO DCTO</b></br>" + "RE" + "</td>";
          infoRecibo += "          </tr></table></td>";
          infoRecibo += "      </tr>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td colspan='2'>";
          infoRecibo += "          <table width='100%'>";
          infoRecibo += "            <tr><td><b>DIRECCION:</b>" + element.pendiente.Paciente.Direccion + "</td><td><b>BARRIO:</b>" + element.pendiente.Paciente.Barrio + "</td></tr>";
          infoRecibo += "            <tr><td><b>TELEFONO:</b>" + element.pendiente.Paciente.Telefono + "</td><td><b>CELULAR:</b>" + element.pendiente.Paciente.Celular + "</td></tr>";
          infoRecibo += "            <tr><td colspan='3' height={'50'}><b>OBSERVACIONES:</b>" + element.pendiente.Paciente.Comentario + "</td></tr>";
          infoRecibo += "          </table></td>";
          infoRecibo += "     </tr>";
          infoRecibo += "    </table>";
          infoRecibo += "    </br>";
          infoRecibo += "<table border={'1px solid black;'} width='100%'>";
          infoRecibo += "       <tr>";
          infoRecibo += "        <th>Orden</th>";
          infoRecibo += "        <th>Descripcion</th>";
          infoRecibo += "        <th>Cantidad</th>";
          infoRecibo += "        <th>Vr. Unitario</th>";
          infoRecibo += "        <th>Total</th></tr>";
          infoRecibo += "      <tbody>";
          let TpEntregaMvto = element.mvPendiente ? element.mvPendiente : (element.mvPendientes ? element.mvPendiente : null);
          TpEntregaMvto.forEach(elemento => {
            infoRecibo += " <tr>";
            infoRecibo += "          <td>" + elemento.Orden + "</td>";
            infoRecibo += "          <td>" + elemento.Nombre + "</td>";
            infoRecibo += "          <td>" + elemento.QtyEntrega + "</td>";
            infoRecibo += "          <td>" + element.pendiente.Convenio.Interop ? '' : formatCurrency('en-US', 'USD', 0, elemento.Valor) + "</td>";
            infoRecibo += "          <td>" + element.pendiente.Convenio.Interop ? '' : formatCurrency('en-US', 'USD', 0, (elemento.Valor * elemento.QtyEntrega)) + "</td>";
            infoRecibo += "        </tr>";
          });
          infoRecibo += "</tbody>";
          infoRecibo += "<tfoot>";
          infoRecibo += "        <tr>";
          infoRecibo += "          <td></td>";
          infoRecibo += "          <td>Cuota moderadora</td>";
          infoRecibo += "          <td></td>";
          infoRecibo += "          <td> " + formatCurrency('en-US', 'USD', 0, element.pendiente.ValorCM) + "</td>";
          infoRecibo += "          <td></td>";
          infoRecibo += "        </tr>";
          infoRecibo += "        <tr>";
          infoRecibo += "          <td></td>";
          infoRecibo += "          <td>Valor a Pagado</td>";
          infoRecibo += "          <td></td>";
          infoRecibo += "          <td>" + formatCurrency('en-US', 'USD', 0, element.pendiente.Pagado) + "</td>";
          infoRecibo += "          <td></td>";
          infoRecibo += "        </tr>";
          infoRecibo += "      </tfoot>";
          infoRecibo += "    </table>";
          infoRecibo += "    </br>";
          infoRecibo += "<table width='100%'>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td>___" + element.pendiente.IdUser_Ing + "___</td>";
          infoRecibo += "        <td>_______________________________________________________</td>";
          infoRecibo += "        <td>________________________________</td>";
          infoRecibo += "      </tr>";
          infoRecibo += "      <tr>";
          infoRecibo += "        <td>Elaborado Por</td>";
          infoRecibo += "        <td>Nombre Quien Recibe</td>";
          infoRecibo += "        <td>Identificacion Quien Recibe</td>";
          infoRecibo += "      </tr>";
          infoRecibo += "    </table>";
        }
      });
    }
    console.log(infoRecibo);
  });
  return infoRecibo;
}