export const defaultValuesMedicamento =
{
  esCopia: false,
  pluOrden: '',
  IdMedicamento: '',
  medicamento: '',
  lote: '',
  FhVtoRInv: '',
  cantidadDisponible: 0,
  cantidadAutorizada: 0,
  cantidadEntregada: 0,
  diasTratamiento: 30,
  mipres: '',
  idSiNo: '',
  valor: 0,
  iva: 0,
  total: 0,
  Lasa: false,
  IdLasa: '',
  Regulado: false,
  Controlado: false,
  Aplicacion: false,
  Fotosensible: false,
  Frio: false,
  Agotado: false,
  alertas: false,
}
